version: '3.7'

services:
  web:
    build: .
    command: bash -c "python3 manage.py migrate --noinput
             && python3 manage.py loaddata fixtures/data_dump.json
             && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./aola:/app/
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aola_db
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-db-volume: