# Generated by Django 4.1.7 on 2023-03-26 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notion',
            new_name='Note',
        ),
        migrations.RenameField(
            model_name='achievement',
            old_name='name',
            new_name='title',
        ),
    ]
