# Generated by Django 4.1.7 on 2023-03-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_notion_note_rename_name_achievement_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images/achievements/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/ad/%Y/%m/%d'),
        ),
    ]
