# Generated by Django 4.1.7 on 2023-03-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_achievement_icon_ad_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='owners',
            field=models.ManyToManyField(through='main.UsersAchievements', to='main.user'),
        ),
    ]
